version: "3.8"
services:
  
  db:
    image: "bitnami/postgresql:11.14.0-debian-10-r0"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo

volumes:
  postgres_data:
